#!/bin/bash

set -e

DOCKER_MIRROR_HOST=$(/sbin/ip route|awk '/default/ { print $3 }')
DOCKER_MIRROR_PORT=${MIRROR_PORT:-9001}
DOCKER_MIRROR="http://$DOCKER_MIRROR_HOST:$DOCKER_MIRROR_PORT"

export HOST_IP=$(curl $DOCKER_MIRROR/hostip)    

if [[ ! -e "$APP_PORT" ]]
then
    export HOST_PORT=$(curl $DOCKER_MIRROR/container/$HOSTNAME/port/$APP_PORT)
fi

exec "$@"